<?php

namespace HomeBundle\Repository;

/**
 * HelloWorldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelloWorldRepository extends \Doctrine\ORM\EntityRepository
{
}
